import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useState } from "react";
import { AwardList } from "../components/molecules/AwardList";
import { Modal } from "../components/molecules/Modal";
import { VoteProvider } from "../store/voteContext";
import styles from "./index.module.css";

const Home: NextPage = () => {
  const [showModal, setShowModal] = useState(false);

  const display = useCallback(() => {
    setShowModal(true);
  }, [setShowModal]);

  const dismiss = useCallback(() => {
    setShowModal(false);
  }, [setShowModal]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <h1 className={styles.pageTitle}>Awards 2021</h1>
        </header>
        {
          <VoteProvider>
            <AwardList showModal={display} />
            {showModal && <Modal dismiss={dismiss} />}
          </VoteProvider>
        }
      </main>
    </div>
  );
};

export default Home;
